### PR TITLE
quality(findbugs) makes findbug annotations `implementation` dependency

### PR DESCRIPTION
**Pull request by NemoOudeis**
addresses #45

### CODE REVIEW

**Comment by jcayzac** [comment]
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

>  The `api` configuration should be used to declare dependencies which are exported by the library API, whereas the `implementation` configuration should be used to declare dependencies which are internal to the component.

We want to _export_ the findbugs suppressions to client projects, so I disagree with using `implementation` here. The annotations should be `api`, and maybe mandate a `-dontnote` line in the consumer proguard files.

**Comment by NemoOudeis** [comment]
Why do you need to export the dependency as part of your public API?
Which annotations of findbugs are always part of your public API?
> An API dependency is one that contains at least one type that is exposed in the library binary interface, often referred to as its ABI (Application Binary Interface)
I would argue that by default that is not the case.

**Comment by jcayzac** [comment]
You asked for my opinion :)

**Comment by jcayzac** [comment]
It's true that gradle's non-semantic, always-optimist-unless-forced-not-to-be way of resolving dependencies makes `api` kind of useless anyway :'(

**Pull request merged**
